### ISSUE TITLE
Update ci-build template

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper-maven-plugin#180]
```
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
```

+ Remove:
```
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
```
