### ISSUE TITLE
Add dependabot configuration for GitHub Actions

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper-maven-plugin#181]
See example https://github.com/itsallcode/openfasttrace/blob/develop/.github/dependabot.yml

```yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

See documentation: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval
