### ISSUE TITLE
Add Caching for Sonar execution

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper-maven-plugin#191]
```yml
      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
```
