### ISSUE TITLE
Use cache of java-setup github action

### ISSUE THREAD

**Issue by morazow** [exasol/project-keeper-maven-plugin#213]
Use cache parameter for maven builds when setting Java in Github actions.

```
steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
  with:
    distribution: 'temurin'
    java-version: '11'
    cache: 'maven'
- name: Build with Maven
  run: mvn -B package --file pom.xml
```
